services:
  - type: web
    name: roblox-api
    env: dotnet
    plan: free
    branch: main
    buildCommand: dotnet build
    startCommand: dotnet run --urls=http://0.0.0.0:10000
    autoDeploy: true
